### ISSUE TITLE
Item "Heart of Wyrmthalak" procs on self

### ISSUE THREAD

**Issue by oj449** [ValorenWoW/sunstrider-issues#615] opened 2019-02-15 04:12 UTC
**Description:**
Procs proc when they shouldn't and hit yourself

**Current behaviour:**

when using stances as a warrior, proc effects will not only proc, they will hit you for damage aswell, i was using stance swaps then hurt myself, the starter warrior trinket was hurting me.

**Expected behaviour:**

procs should not hit yourself off stances, potentially other abilities not sure.

**Steps to reproduce the problem:**
[](https://imgur.com/a/qESs4vr) visual
1. equip proc trinket, try just making a starter warrior and equipping the starter 58 set, learning stances and spamming
2. spam stance swaps
3. you hurt yourself in confusion
![visual](https://user-images.githubusercontent.com/47352954/52835684-2bd54100-3133-11e9-851d-fce77bdd71c5.png)
this just now procced with that trinket and hand of justice

**Comment by Jerrythemagicdog** [comment] 2019-02-15 04:38
Can't reproduce, please provide a screenshot or copy paste of the combat log. "Proc trinket" means Hand of Justice?

**Comment by oj449** [comment] 2019-02-15 05:06
updated

**Comment by oj449** [comment] 2019-02-15 05:49
it could be stances incorrectly triggering trinkets or an issue with trinket procs themselves

**Comment by Jerrythemagicdog** [comment] 2019-02-15 08:46
Could you also include server rev? Do a .server info in game and paste / screenshot the numer after "Sunstrider rev."
I can't seem to reproduce this bug

**Comment by oj449** [comment] 2019-02-15 08:57
![serverr](https://user-images.githubusercontent.com/47352954/52845575-31428380-3153-11e9-9304-56ca70345c78.png)
![wowscrnshot_021519_185532](https://user-images.githubusercontent.com/47352954/52845708-7bc40000-3153-11e9-9fdd-4ff0c84536aa.jpg)
![wowscrnshot_021519_185623](https://user-images.githubusercontent.com/47352954/52845710-7c5c9680-3153-11e9-90c4-c17ed6236aa4.jpg)
![wowscrnshot_021519_185641](https://user-images.githubusercontent.com/47352954/52845711-7c5c9680-3153-11e9-9e6e-7d7caa718bb9.jpg)
it takes a bit of spamming between stances to proc the trinkets, can be straight away or after 30+ attempts.

**Comment by Jerrythemagicdog** [comment] 2019-02-15 09:10
Thanks!

**Comment by oj449** [comment] 2019-02-15 09:30
[2019-02-15 19-24-26.zip](https://github.com/ValorenWoW/sunstrider-issues/files/2868630/2019-02-15.19-24-26.zip)
video of it occuring

**Comment by Jerrythemagicdog** [comment] 2019-02-15 09:58
> Larry gains Berserker Stance.
> Berserker Stance fades from Larry.
> Larry gains Defensive Stance.
> Defensive Stance fades from Larry.
> Larry gains Berserker Stance.
> Larry's Flame Lash hits Larry for 183 Fire.
> Berserker Stance fades from Larry.
> Larry gains Battle Stance.

**Comment by oj449** [comment] 2019-02-15 10:26
i feel it could be a thing that the stances are being coded as self targeted melee hits, so that all the proc types for trinket and perhaps other items are proccing for those types, so any on melee hit proc chance trinket may be able to proc off stance swapping.

**Comment by kelno** [comment] 2019-02-15 12:18
Thanks!
That's something that need to be fixed per spell, not a general issue. I'll rename the issue to reflect that.

**Comment by Jerrythemagicdog** [comment] 2019-02-16 09:24
Fixed in rev 10490

**Closed** 2019-02-16 09:24 UTC
Labels: bug, doublechecked, spells
